import { parseAbi } from "viem";

// Kept in human-readable form so the frontend can be reviewed against the
// immutable Solidity API. scripts/export-abi.mjs can replace this with the
// Foundry artifact ABI after compilation without changing call sites.
export const uniskyPassAbi = parseAbi([
  "error AlreadyRegistered()",
  "error NotRegisteredIssuer()",
  "error InvalidName()",
  "error InvalidDuration()",
  "error InvalidValidFrom()",
  "error ZeroHolder()",
  "error ProgramNotFound()",
  "error ProgramInactive()",
  "error NotProgramIssuer()",
  "error PassNotFound()",
  "error NotPassIssuer()",
  "error PassIsRevoked()",
  "event IssuerRegistered(address indexed issuer, string name)",
  "event IssuerNameUpdated(address indexed issuer, string name)",
  "event ProgramCreated(uint256 indexed programId, address indexed issuer, string name, uint64 duration)",
  "event ProgramActiveSet(uint256 indexed programId, bool active)",
  "event PassIssued(uint256 indexed passId, uint256 indexed programId, address indexed holder, address issuer, uint64 validFrom, uint64 expiresAt)",
  "event PassExtended(uint256 indexed passId, uint64 newExpiresAt)",
  "event PassRevoked(uint256 indexed passId)",
  "function MAX_NAME_BYTES() view returns (uint256)",
  "function MAX_DURATION() view returns (uint64)",
  "function programCount() view returns (uint256)",
  "function passCount() view returns (uint256)",
  "function registerIssuer(string name)",
  "function updateIssuerName(string name)",
  "function createProgram(string name, uint64 duration) returns (uint256 programId)",
  "function setProgramActive(uint256 programId, bool active)",
  "function issuePass(uint256 programId, address holder, uint64 validFrom) returns (uint256 passId)",
  "function extendPass(uint256 passId, uint64 extraSeconds)",
  "function revokePass(uint256 passId)",
  "function getIssuer(address issuer) view returns ((string name, uint64 registeredAt, bool exists))",
  "function isIssuer(address issuer) view returns (bool)",
  "function getProgram(uint256 programId) view returns ((address issuer, uint64 duration, bool active, string name))",
  "function getPass(uint256 passId) view returns ((uint256 programId, address issuer, address holder, uint64 issuedAt, uint64 validFrom, uint64 expiresAt, bool revoked))",
  "function getIssuerPrograms(address issuer) view returns (uint256[])",
  "function getHolderPasses(address holder) view returns (uint256[])",
  "function getProgramPasses(uint256 programId) view returns (uint256[])",
  "function isPassValid(uint256 passId) view returns (bool)",
  "function getPassStatus(uint256 passId) view returns (uint8)",
  "function isPassValidFor(uint256 passId, address expectedHolder, address expectedIssuer, uint256 expectedProgramId) view returns (bool)",
]);
